image: alpine/edge
packages:
  - unzip
  - curl
secrets:
  - 1395de5b-a4f1-452a-9825-5e82a18d656c
sources:
  - https://git.sr.ht/~jordanreger/smdatabase
tasks:
  - install-deno: |
      curl -fsSL https://deno.land/x/install/install.sh | sh
  - install-deployctl: |
      export DENO_INSTALL="/home/build/.deno"
      export PATH="$DENO_INSTALL/bin:$PATH"
      deno install -Arf jsr:@deno/deployctl
  - deploy: |
      set +x
      DENO_DEPLOY_TOKEN=$(cat ~/.deno_deploy_token)
      set -x
      export DENO_INSTALL="/home/build/.deno"
      export PATH="$DENO_INSTALL/bin:$PATH"
      cd smdatabase
      deployctl deploy
