// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_addPart from "./routes/api/addPart.tsx";
import * as $api_updatePart from "./routes/api/updatePart.tsx";
import * as $home from "./routes/home.tsx";
import * as $index from "./routes/index.tsx";
import * as $parts from "./routes/parts.tsx";
import * as $AddPartButton from "./islands/AddPartButton.tsx";
import * as $EditPartButton from "./islands/EditPartButton.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $PartCSVButton from "./islands/PartCSVButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/addPart.tsx": $api_addPart,
    "./routes/api/updatePart.tsx": $api_updatePart,
    "./routes/home.tsx": $home,
    "./routes/index.tsx": $index,
    "./routes/parts.tsx": $parts,
  },
  islands: {
    "./islands/AddPartButton.tsx": $AddPartButton,
    "./islands/EditPartButton.tsx": $EditPartButton,
    "./islands/Header.tsx": $Header,
    "./islands/PartCSVButton.tsx": $PartCSVButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
